# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 84ef4de4b0d5a64709c8c7d294fe5c6c5f6f66ac533e3711707c8df8becdded7476e6db5e1136fbf701ca9ac5c3657a444ecd0346d2269d0a7ab81424461f3f9

test:
  secret_key_base: 64d09fef4d6da7890514dc4b9cfb3e91cf3433ac82410d8728a278b710a369dd7c60c832e1eeee860b33ad6d04e27f9d80ebbc63cf78e861a9af078999d8838b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
